export const mainEntries = [
    "Movies",
    "TV Shows"
]

export const genres = [
    "Action",
    "Animation",
    "Biography",
    "Comedy",
    "Crime",
    "Documentary",
    "Drama",
    "Family",
    "Fantasy",
    "History",
    "Horror",
    "Kids",
    "Music",
    "Musical",
    "Mystery",
    "Reality",
    "Romance",
    "Sci-Fi",
    "Sport",
    "Thriller",
    "War",
    "Western"
]

export const bestEntries = [
    "Best 2025",
    "Best 2022 TV shows",
    "Best 2023 TV shows",
    "Best 2024 TV shows",
    "Best 2025 TV shows",
    "Best TV mini-series",
    "Best Netflix Series",
    "Best Reality-Shows",
    "Best Movies",
    "Best 2024",
    "Best 2023",
    "Best 2022",
    "Best 2021",
    "Best 2020",
    "Best 2019",
    "Best 2018",
    "Best 2017",
    "Best 2016",
    "Best Action 2021",
    "Best Action 2023",
    "Best Animated 2017",
    "Best Animated 2019",
    "Best Animated 2023",
    "Best Adventure 2021",
    "Best Adventure 2023",
    "Best Biography 2022",
    "Best Biography 2023",
    "Best Comedy 2017",
    "Best Comedy 2022",
    "Best Comedy 2023",
    "Best Crime 2021",
    "Best Crime 2022",
    "Best Crime 2023",
    "Best Documentary 2021",
    "Best Documentaries 2022",
    "Best Documentaries 2023",
    "Best Drama 2019",
    "Best Drama 2021",
    "Best Drama 2023",
    "Best Family 2021",
    "Best Family 2023",
    "Best Fantasy & Sci-fi 2021",
    "Best Fantasy & Sci-fi 2023",
    "Best History 2021",
    "Best History 2022",
    "Best History 2023",
    "Best History 2023",
    "Best Horror 2023",
    "Best Musical 2022",
    "Best Mystery 2021",
    "Best Mystery 2022",
    "Best Mystery 2023",
    "Best Romantic 2021",
    "Best Romantic 2022",
    "Best Romantic 2023",
    "Best Thriller 2021",
    "Best Thriller 2022",
    "Best 2010s Body Horror",
    "Best War 2021",
    "Best War 2022",
    "Best War 2023",
    "Best Anime Movies",
    "Best Chick Flick",
    "Best Disney Princess",
    "Best Existential",
    "Best German",
    "Best Franchise",
    "Best Japanese",
    "Best Loners",
    "Best Netflix Movies",
    "Best Songs from Movies"
]

export const subEntries = [
    "2025",
    "Best 2024",
    "Trending Movies",
    "Top Most Popular Movies",
    "Oscar",
    "Golden Globe",
    "Box Office in All Times",
    "TV Shows",
    "Top Most Popular TVs",
    "Trending TV Shows",
    "Best 2022 TV shows",
    "Best 2023 TV shows",
    "Best TV mini-series",
    "Best Netflix Series",
    "Best Reality-Shows",
    "Top 250 Movies",
    "Top 250 TVs",
    "Best 2016",
    "Best 2017",
    "Best 2018",
    "Best 2019",
    "Best 2020",
    "Best 2021",
    "Best 2022",
    "Best 2023",
    "Best Action 2021",
    "Best Action 2023",
    "Best Animated 2017",
    "Best Animated 2019",
    "Best Animated 2023",
    "Best Adventure 2021",
    "Best Adventure 2023",
    "Best Biography 2022",
    "Best Biography 2023",
    "Best Comedy 2017",
    "Best Comedy 2022",
    "Best Comedy 2023",
    "Best Crime 2021",
    "Best Crime 2022",
    "Best Crime 2023",
    "Best Documentary 2021",
    "Best Documentaries 2022",
    "Best Documentaries 2023",
    "Best Drama 2019",
    "Best Drama 2021",
    "Best Drama 2023",
    "Best Family 2021",
    "Best Family 2023",
    "Best Fantasy & Sci-fi 2021",
    "Best Fantasy & Sci-fi 2023",
    "Best History 2021",
    "Best History 2022",
    "Best History 2023",
    "Best History 2023",
    "Best Horror 2023",
    "Best Musical 2022",
    "Best Mystery 2021",
    "Best Mystery 2022",
    "Best Mystery 2023",
    "Best Romantic 2021",
    "Best Romantic 2022",
    "Best Romantic 2023",
    "Best Thriller 2021",
    "Best Thriller 2022",
    "Best 2010s Body Horror",
    "Best War 2021",
    "Best War 2022",
    "Best War 2023",
    "2024 Highest Grossing",
    "2023 Highest Grossing",
    "2022 Highest Grossing",
    "Animated for Kids",
    "Artificial Intelligence",
    "Action Comedies",
    "Batman",
    "Best Anime Movies",
    "Best Chick Flick",
    "Best Disney Princess",
    "Best Existential",
    "Best German",
    "Best Franchise",
    "Best Japanese",
    "Best Loners",
    "Best Netflix Movies",
    "Best Songs from Movies",
    "DC Comics",
    "Feminist",
    "Fast and Furious",
    "Gay",
    "Good Cop/Bad Cop",
    "Greatest Remakes",
    "James Bond",
    "Mardi Gras",
    "Marvel",
    "Most Inspirational",
    "Most Rewatchable",
    "Palme d’Or winners",
    "Funniest 2010s Horror",
    "Harry Potter",
    "Martin Luther King",
    "Oldest Profession Movies",
    "Oscar 2019",
    "Oscar 2020",
    "Oscar 2021",
    "Oscar 2024",
    "Pixar",
    "Racism and Movies",
    "Saw Movies",
    "Space",
    "Spider-Man",
    "Superman"
]

export function getRandomUnique<T>(arr: T[], count: number): T[] {
    // Shuffle a copy of the array and take the first 'count' elements
    return arr
        .slice()
        .sort(() => 0.5 - Math.random())
        .slice(0, Math.min(count, arr.length));
}

export function getCombinedEntries(n: number, k: number, i: number): string[] {
    const selectedGenres = getRandomUnique(genres, n);
    const selectedBest = getRandomUnique(bestEntries, k);
    const selectedSub = getRandomUnique(subEntries, i);
    return [...mainEntries, ...selectedGenres, ...selectedBest, ...selectedSub];
}

export function getRandomInteger(min: number, max: number): number {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}